import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/page'
import localFont from 'next/font/local'

const futura = localFont({
  src: [
    {
      path: '../../public/fonts/Poppins-Bold.otf',
      weight: '400'
    },

  ],
  variable: '--font-futura'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={` scroll-smooth `} lang="en">
     
      <body className={`${inter.className} `}>{children}</body>
    </html>
  )
}
